// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 1otsp_root.proto

package com.tokbox.tumor.proto;

public final class OtspCore {
  private OtspCore() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface OtspMessageOrBuilder extends
      com.google.protobuf.GeneratedMessage.
          ExtendableMessageOrBuilder<OtspMessage> {
    
    // optional .otsp.OtspMessage.Topology topology = 1 [default = UNICAST];
    boolean hasTopology();
    com.tokbox.tumor.proto.OtspCore.OtspMessage.Topology getTopology();
    
    // optional .otsp.OtspNodeAddress from = 2;
    boolean hasFrom();
    com.tokbox.tumor.proto.OtspCore.OtspNodeAddress getFrom();
    com.tokbox.tumor.proto.OtspCore.OtspNodeAddressOrBuilder getFromOrBuilder();
    
    // optional .otsp.OtspNodeAddress to = 3;
    boolean hasTo();
    com.tokbox.tumor.proto.OtspCore.OtspNodeAddress getTo();
    com.tokbox.tumor.proto.OtspCore.OtspNodeAddressOrBuilder getToOrBuilder();
    
    // optional uint32 mask = 4;
    boolean hasMask();
    int getMask();
    
    // optional uint32 id = 5;
    boolean hasId();
    int getId();
  }
  public static final class OtspMessage extends
      com.google.protobuf.GeneratedMessage.ExtendableMessage<
        OtspMessage> implements OtspMessageOrBuilder {
    // Use OtspMessage.newBuilder() to construct.
    private OtspMessage(Builder builder) {
      super(builder);
    }
    private OtspMessage(boolean noInit) {}
    
    private static final OtspMessage defaultInstance;
    public static OtspMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public OtspMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tokbox.tumor.proto.OtspCore.internal_static_otsp_OtspMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tokbox.tumor.proto.OtspCore.internal_static_otsp_OtspMessage_fieldAccessorTable;
    }
    
    public enum Topology
        implements com.google.protobuf.ProtocolMessageEnum {
      UNICAST(0, 1),
      ANYCAST(1, 2),
      MULTICAST(2, 3),
      BROADCAST(3, 4),
      ;
      
      public static final int UNICAST_VALUE = 1;
      public static final int ANYCAST_VALUE = 2;
      public static final int MULTICAST_VALUE = 3;
      public static final int BROADCAST_VALUE = 4;
      
      
      public final int getNumber() { return value; }
      
      public static Topology valueOf(int value) {
        switch (value) {
          case 1: return UNICAST;
          case 2: return ANYCAST;
          case 3: return MULTICAST;
          case 4: return BROADCAST;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Topology>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Topology>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Topology>() {
              public Topology findValueByNumber(int number) {
                return Topology.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.tokbox.tumor.proto.OtspCore.OtspMessage.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Topology[] VALUES = {
        UNICAST, ANYCAST, MULTICAST, BROADCAST, 
      };
      
      public static Topology valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Topology(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:otsp.OtspMessage.Topology)
    }
    
    private int bitField0_;
    // optional .otsp.OtspMessage.Topology topology = 1 [default = UNICAST];
    public static final int TOPOLOGY_FIELD_NUMBER = 1;
    private com.tokbox.tumor.proto.OtspCore.OtspMessage.Topology topology_;
    public boolean hasTopology() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.tokbox.tumor.proto.OtspCore.OtspMessage.Topology getTopology() {
      return topology_;
    }
    
    // optional .otsp.OtspNodeAddress from = 2;
    public static final int FROM_FIELD_NUMBER = 2;
    private com.tokbox.tumor.proto.OtspCore.OtspNodeAddress from_;
    public boolean hasFrom() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.tokbox.tumor.proto.OtspCore.OtspNodeAddress getFrom() {
      return from_;
    }
    public com.tokbox.tumor.proto.OtspCore.OtspNodeAddressOrBuilder getFromOrBuilder() {
      return from_;
    }
    
    // optional .otsp.OtspNodeAddress to = 3;
    public static final int TO_FIELD_NUMBER = 3;
    private com.tokbox.tumor.proto.OtspCore.OtspNodeAddress to_;
    public boolean hasTo() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public com.tokbox.tumor.proto.OtspCore.OtspNodeAddress getTo() {
      return to_;
    }
    public com.tokbox.tumor.proto.OtspCore.OtspNodeAddressOrBuilder getToOrBuilder() {
      return to_;
    }
    
    // optional uint32 mask = 4;
    public static final int MASK_FIELD_NUMBER = 4;
    private int mask_;
    public boolean hasMask() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getMask() {
      return mask_;
    }
    
    // optional uint32 id = 5;
    public static final int ID_FIELD_NUMBER = 5;
    private int id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getId() {
      return id_;
    }
    
    private void initFields() {
      topology_ = com.tokbox.tumor.proto.OtspCore.OtspMessage.Topology.UNICAST;
      from_ = com.tokbox.tumor.proto.OtspCore.OtspNodeAddress.getDefaultInstance();
      to_ = com.tokbox.tumor.proto.OtspCore.OtspNodeAddress.getDefaultInstance();
      mask_ = 0;
      id_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (hasFrom()) {
        if (!getFrom().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasTo()) {
        if (!getTo().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      com.google.protobuf.GeneratedMessage
        .ExtendableMessage<com.tokbox.tumor.proto.OtspCore.OtspMessage>.ExtensionWriter extensionWriter =
          newExtensionWriter();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, topology_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, from_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, to_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, mask_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt32(5, id_);
      }
      extensionWriter.writeUntil(100, output);
      extensionWriter.writeUntil(1000, output);
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, topology_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, from_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, to_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, mask_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, id_);
      }
      size += extensionsSerializedSize();
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.tokbox.tumor.proto.OtspCore.OtspMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspCore.OtspMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspCore.OtspMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspCore.OtspMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspCore.OtspMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspCore.OtspMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspCore.OtspMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.tokbox.tumor.proto.OtspCore.OtspMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.tokbox.tumor.proto.OtspCore.OtspMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspCore.OtspMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.tokbox.tumor.proto.OtspCore.OtspMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.ExtendableBuilder<
          com.tokbox.tumor.proto.OtspCore.OtspMessage, Builder> implements com.tokbox.tumor.proto.OtspCore.OtspMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tokbox.tumor.proto.OtspCore.internal_static_otsp_OtspMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tokbox.tumor.proto.OtspCore.internal_static_otsp_OtspMessage_fieldAccessorTable;
      }
      
      // Construct using com.tokbox.tumor.proto.OtspCore.OtspMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getFromFieldBuilder();
          getToFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        topology_ = com.tokbox.tumor.proto.OtspCore.OtspMessage.Topology.UNICAST;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (fromBuilder_ == null) {
          from_ = com.tokbox.tumor.proto.OtspCore.OtspNodeAddress.getDefaultInstance();
        } else {
          fromBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (toBuilder_ == null) {
          to_ = com.tokbox.tumor.proto.OtspCore.OtspNodeAddress.getDefaultInstance();
        } else {
          toBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        mask_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tokbox.tumor.proto.OtspCore.OtspMessage.getDescriptor();
      }
      
      public com.tokbox.tumor.proto.OtspCore.OtspMessage getDefaultInstanceForType() {
        return com.tokbox.tumor.proto.OtspCore.OtspMessage.getDefaultInstance();
      }
      
      public com.tokbox.tumor.proto.OtspCore.OtspMessage build() {
        com.tokbox.tumor.proto.OtspCore.OtspMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.tokbox.tumor.proto.OtspCore.OtspMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.tokbox.tumor.proto.OtspCore.OtspMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.tokbox.tumor.proto.OtspCore.OtspMessage buildPartial() {
        com.tokbox.tumor.proto.OtspCore.OtspMessage result = new com.tokbox.tumor.proto.OtspCore.OtspMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.topology_ = topology_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (fromBuilder_ == null) {
          result.from_ = from_;
        } else {
          result.from_ = fromBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (toBuilder_ == null) {
          result.to_ = to_;
        } else {
          result.to_ = toBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.mask_ = mask_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.id_ = id_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tokbox.tumor.proto.OtspCore.OtspMessage) {
          return mergeFrom((com.tokbox.tumor.proto.OtspCore.OtspMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.tokbox.tumor.proto.OtspCore.OtspMessage other) {
        if (other == com.tokbox.tumor.proto.OtspCore.OtspMessage.getDefaultInstance()) return this;
        if (other.hasTopology()) {
          setTopology(other.getTopology());
        }
        if (other.hasFrom()) {
          mergeFrom(other.getFrom());
        }
        if (other.hasTo()) {
          mergeTo(other.getTo());
        }
        if (other.hasMask()) {
          setMask(other.getMask());
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (hasFrom()) {
          if (!getFrom().isInitialized()) {
            
            return false;
          }
        }
        if (hasTo()) {
          if (!getTo().isInitialized()) {
            
            return false;
          }
        }
        if (!extensionsAreInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.tokbox.tumor.proto.OtspCore.OtspMessage.Topology value = com.tokbox.tumor.proto.OtspCore.OtspMessage.Topology.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                topology_ = value;
              }
              break;
            }
            case 18: {
              com.tokbox.tumor.proto.OtspCore.OtspNodeAddress.Builder subBuilder = com.tokbox.tumor.proto.OtspCore.OtspNodeAddress.newBuilder();
              if (hasFrom()) {
                subBuilder.mergeFrom(getFrom());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setFrom(subBuilder.buildPartial());
              break;
            }
            case 26: {
              com.tokbox.tumor.proto.OtspCore.OtspNodeAddress.Builder subBuilder = com.tokbox.tumor.proto.OtspCore.OtspNodeAddress.newBuilder();
              if (hasTo()) {
                subBuilder.mergeFrom(getTo());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setTo(subBuilder.buildPartial());
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              mask_ = input.readUInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              id_ = input.readUInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional .otsp.OtspMessage.Topology topology = 1 [default = UNICAST];
      private com.tokbox.tumor.proto.OtspCore.OtspMessage.Topology topology_ = com.tokbox.tumor.proto.OtspCore.OtspMessage.Topology.UNICAST;
      public boolean hasTopology() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.tokbox.tumor.proto.OtspCore.OtspMessage.Topology getTopology() {
        return topology_;
      }
      public Builder setTopology(com.tokbox.tumor.proto.OtspCore.OtspMessage.Topology value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        topology_ = value;
        onChanged();
        return this;
      }
      public Builder clearTopology() {
        bitField0_ = (bitField0_ & ~0x00000001);
        topology_ = com.tokbox.tumor.proto.OtspCore.OtspMessage.Topology.UNICAST;
        onChanged();
        return this;
      }
      
      // optional .otsp.OtspNodeAddress from = 2;
      private com.tokbox.tumor.proto.OtspCore.OtspNodeAddress from_ = com.tokbox.tumor.proto.OtspCore.OtspNodeAddress.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.tokbox.tumor.proto.OtspCore.OtspNodeAddress, com.tokbox.tumor.proto.OtspCore.OtspNodeAddress.Builder, com.tokbox.tumor.proto.OtspCore.OtspNodeAddressOrBuilder> fromBuilder_;
      public boolean hasFrom() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.tokbox.tumor.proto.OtspCore.OtspNodeAddress getFrom() {
        if (fromBuilder_ == null) {
          return from_;
        } else {
          return fromBuilder_.getMessage();
        }
      }
      public Builder setFrom(com.tokbox.tumor.proto.OtspCore.OtspNodeAddress value) {
        if (fromBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          from_ = value;
          onChanged();
        } else {
          fromBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setFrom(
          com.tokbox.tumor.proto.OtspCore.OtspNodeAddress.Builder builderForValue) {
        if (fromBuilder_ == null) {
          from_ = builderForValue.build();
          onChanged();
        } else {
          fromBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeFrom(com.tokbox.tumor.proto.OtspCore.OtspNodeAddress value) {
        if (fromBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              from_ != com.tokbox.tumor.proto.OtspCore.OtspNodeAddress.getDefaultInstance()) {
            from_ =
              com.tokbox.tumor.proto.OtspCore.OtspNodeAddress.newBuilder(from_).mergeFrom(value).buildPartial();
          } else {
            from_ = value;
          }
          onChanged();
        } else {
          fromBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearFrom() {
        if (fromBuilder_ == null) {
          from_ = com.tokbox.tumor.proto.OtspCore.OtspNodeAddress.getDefaultInstance();
          onChanged();
        } else {
          fromBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public com.tokbox.tumor.proto.OtspCore.OtspNodeAddress.Builder getFromBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getFromFieldBuilder().getBuilder();
      }
      public com.tokbox.tumor.proto.OtspCore.OtspNodeAddressOrBuilder getFromOrBuilder() {
        if (fromBuilder_ != null) {
          return fromBuilder_.getMessageOrBuilder();
        } else {
          return from_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.tokbox.tumor.proto.OtspCore.OtspNodeAddress, com.tokbox.tumor.proto.OtspCore.OtspNodeAddress.Builder, com.tokbox.tumor.proto.OtspCore.OtspNodeAddressOrBuilder> 
          getFromFieldBuilder() {
        if (fromBuilder_ == null) {
          fromBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.tokbox.tumor.proto.OtspCore.OtspNodeAddress, com.tokbox.tumor.proto.OtspCore.OtspNodeAddress.Builder, com.tokbox.tumor.proto.OtspCore.OtspNodeAddressOrBuilder>(
                  from_,
                  getParentForChildren(),
                  isClean());
          from_ = null;
        }
        return fromBuilder_;
      }
      
      // optional .otsp.OtspNodeAddress to = 3;
      private com.tokbox.tumor.proto.OtspCore.OtspNodeAddress to_ = com.tokbox.tumor.proto.OtspCore.OtspNodeAddress.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.tokbox.tumor.proto.OtspCore.OtspNodeAddress, com.tokbox.tumor.proto.OtspCore.OtspNodeAddress.Builder, com.tokbox.tumor.proto.OtspCore.OtspNodeAddressOrBuilder> toBuilder_;
      public boolean hasTo() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public com.tokbox.tumor.proto.OtspCore.OtspNodeAddress getTo() {
        if (toBuilder_ == null) {
          return to_;
        } else {
          return toBuilder_.getMessage();
        }
      }
      public Builder setTo(com.tokbox.tumor.proto.OtspCore.OtspNodeAddress value) {
        if (toBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          to_ = value;
          onChanged();
        } else {
          toBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder setTo(
          com.tokbox.tumor.proto.OtspCore.OtspNodeAddress.Builder builderForValue) {
        if (toBuilder_ == null) {
          to_ = builderForValue.build();
          onChanged();
        } else {
          toBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder mergeTo(com.tokbox.tumor.proto.OtspCore.OtspNodeAddress value) {
        if (toBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              to_ != com.tokbox.tumor.proto.OtspCore.OtspNodeAddress.getDefaultInstance()) {
            to_ =
              com.tokbox.tumor.proto.OtspCore.OtspNodeAddress.newBuilder(to_).mergeFrom(value).buildPartial();
          } else {
            to_ = value;
          }
          onChanged();
        } else {
          toBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder clearTo() {
        if (toBuilder_ == null) {
          to_ = com.tokbox.tumor.proto.OtspCore.OtspNodeAddress.getDefaultInstance();
          onChanged();
        } else {
          toBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      public com.tokbox.tumor.proto.OtspCore.OtspNodeAddress.Builder getToBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getToFieldBuilder().getBuilder();
      }
      public com.tokbox.tumor.proto.OtspCore.OtspNodeAddressOrBuilder getToOrBuilder() {
        if (toBuilder_ != null) {
          return toBuilder_.getMessageOrBuilder();
        } else {
          return to_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.tokbox.tumor.proto.OtspCore.OtspNodeAddress, com.tokbox.tumor.proto.OtspCore.OtspNodeAddress.Builder, com.tokbox.tumor.proto.OtspCore.OtspNodeAddressOrBuilder> 
          getToFieldBuilder() {
        if (toBuilder_ == null) {
          toBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.tokbox.tumor.proto.OtspCore.OtspNodeAddress, com.tokbox.tumor.proto.OtspCore.OtspNodeAddress.Builder, com.tokbox.tumor.proto.OtspCore.OtspNodeAddressOrBuilder>(
                  to_,
                  getParentForChildren(),
                  isClean());
          to_ = null;
        }
        return toBuilder_;
      }
      
      // optional uint32 mask = 4;
      private int mask_ ;
      public boolean hasMask() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getMask() {
        return mask_;
      }
      public Builder setMask(int value) {
        bitField0_ |= 0x00000008;
        mask_ = value;
        onChanged();
        return this;
      }
      public Builder clearMask() {
        bitField0_ = (bitField0_ & ~0x00000008);
        mask_ = 0;
        onChanged();
        return this;
      }
      
      // optional uint32 id = 5;
      private int id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getId() {
        return id_;
      }
      public Builder setId(int value) {
        bitField0_ |= 0x00000010;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        id_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:otsp.OtspMessage)
    }
    
    static {
      defaultInstance = new OtspMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:otsp.OtspMessage)
  }
  
  public interface OtspNodeAddressOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required bytes address = 1;
    boolean hasAddress();
    com.google.protobuf.ByteString getAddress();
  }
  public static final class OtspNodeAddress extends
      com.google.protobuf.GeneratedMessage
      implements OtspNodeAddressOrBuilder {
    // Use OtspNodeAddress.newBuilder() to construct.
    private OtspNodeAddress(Builder builder) {
      super(builder);
    }
    private OtspNodeAddress(boolean noInit) {}
    
    private static final OtspNodeAddress defaultInstance;
    public static OtspNodeAddress getDefaultInstance() {
      return defaultInstance;
    }
    
    public OtspNodeAddress getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tokbox.tumor.proto.OtspCore.internal_static_otsp_OtspNodeAddress_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tokbox.tumor.proto.OtspCore.internal_static_otsp_OtspNodeAddress_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required bytes address = 1;
    public static final int ADDRESS_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString address_;
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.google.protobuf.ByteString getAddress() {
      return address_;
    }
    
    private void initFields() {
      address_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasAddress()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, address_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, address_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.tokbox.tumor.proto.OtspCore.OtspNodeAddress parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspCore.OtspNodeAddress parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspCore.OtspNodeAddress parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspCore.OtspNodeAddress parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspCore.OtspNodeAddress parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspCore.OtspNodeAddress parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspCore.OtspNodeAddress parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.tokbox.tumor.proto.OtspCore.OtspNodeAddress parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.tokbox.tumor.proto.OtspCore.OtspNodeAddress parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspCore.OtspNodeAddress parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.tokbox.tumor.proto.OtspCore.OtspNodeAddress prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.tokbox.tumor.proto.OtspCore.OtspNodeAddressOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tokbox.tumor.proto.OtspCore.internal_static_otsp_OtspNodeAddress_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tokbox.tumor.proto.OtspCore.internal_static_otsp_OtspNodeAddress_fieldAccessorTable;
      }
      
      // Construct using com.tokbox.tumor.proto.OtspCore.OtspNodeAddress.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        address_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tokbox.tumor.proto.OtspCore.OtspNodeAddress.getDescriptor();
      }
      
      public com.tokbox.tumor.proto.OtspCore.OtspNodeAddress getDefaultInstanceForType() {
        return com.tokbox.tumor.proto.OtspCore.OtspNodeAddress.getDefaultInstance();
      }
      
      public com.tokbox.tumor.proto.OtspCore.OtspNodeAddress build() {
        com.tokbox.tumor.proto.OtspCore.OtspNodeAddress result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.tokbox.tumor.proto.OtspCore.OtspNodeAddress buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.tokbox.tumor.proto.OtspCore.OtspNodeAddress result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.tokbox.tumor.proto.OtspCore.OtspNodeAddress buildPartial() {
        com.tokbox.tumor.proto.OtspCore.OtspNodeAddress result = new com.tokbox.tumor.proto.OtspCore.OtspNodeAddress(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.address_ = address_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tokbox.tumor.proto.OtspCore.OtspNodeAddress) {
          return mergeFrom((com.tokbox.tumor.proto.OtspCore.OtspNodeAddress)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.tokbox.tumor.proto.OtspCore.OtspNodeAddress other) {
        if (other == com.tokbox.tumor.proto.OtspCore.OtspNodeAddress.getDefaultInstance()) return this;
        if (other.hasAddress()) {
          setAddress(other.getAddress());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasAddress()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              address_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required bytes address = 1;
      private com.google.protobuf.ByteString address_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.google.protobuf.ByteString getAddress() {
        return address_;
      }
      public Builder setAddress(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        address_ = value;
        onChanged();
        return this;
      }
      public Builder clearAddress() {
        bitField0_ = (bitField0_ & ~0x00000001);
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:otsp.OtspNodeAddress)
    }
    
    static {
      defaultInstance = new OtspNodeAddress(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:otsp.OtspNodeAddress)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_otsp_OtspMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_otsp_OtspMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_otsp_OtspNodeAddress_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_otsp_OtspNodeAddress_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\0201otsp_root.proto\022\004otsp\"\367\001\n\013OtspMessage" +
      "\0225\n\010topology\030\001 \001(\0162\032.otsp.OtspMessage.To" +
      "pology:\007UNICAST\022#\n\004from\030\002 \001(\0132\025.otsp.Ots" +
      "pNodeAddress\022!\n\002to\030\003 \001(\0132\025.otsp.OtspNode" +
      "Address\022\014\n\004mask\030\004 \001(\r\022\n\n\002id\030\005 \001(\r\"B\n\010Top" +
      "ology\022\013\n\007UNICAST\020\001\022\013\n\007ANYCAST\020\002\022\r\n\tMULTI" +
      "CAST\020\003\022\r\n\tBROADCAST\020\004*\004\010\n\020d*\005\010d\020\350\007\"\"\n\017Ot" +
      "spNodeAddress\022\017\n\007address\030\001 \002(\014B\"\n\026com.to" +
      "kbox.tumor.protoB\010OtspCore"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_otsp_OtspMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_otsp_OtspMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_otsp_OtspMessage_descriptor,
              new java.lang.String[] { "Topology", "From", "To", "Mask", "Id", },
              com.tokbox.tumor.proto.OtspCore.OtspMessage.class,
              com.tokbox.tumor.proto.OtspCore.OtspMessage.Builder.class);
          internal_static_otsp_OtspNodeAddress_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_otsp_OtspNodeAddress_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_otsp_OtspNodeAddress_descriptor,
              new java.lang.String[] { "Address", },
              com.tokbox.tumor.proto.OtspCore.OtspNodeAddress.class,
              com.tokbox.tumor.proto.OtspCore.OtspNodeAddress.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
