// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 2otsp_routing.proto

package com.tokbox.tumor.proto;

public final class OtspRouting {
  private OtspRouting() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(com.tokbox.tumor.proto.OtspRouting.groupManagement);
    registry.add(com.tokbox.tumor.proto.OtspRouting.controlManagement);
    registry.add(com.tokbox.tumor.proto.OtspRouting.connectionManagement);
    registry.add(com.tokbox.tumor.proto.OtspRouting.signature);
  }
  public interface GroupManagementOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .otsp.GroupManagement.OpCode opcode = 1;
    boolean hasOpcode();
    com.tokbox.tumor.proto.OtspRouting.GroupManagement.OpCode getOpcode();
    
    // repeated .otsp.OtspNodeAddress addresses = 2;
    java.util.List<com.tokbox.tumor.proto.OtspCore.OtspNodeAddress> 
        getAddressesList();
    com.tokbox.tumor.proto.OtspCore.OtspNodeAddress getAddresses(int index);
    int getAddressesCount();
    java.util.List<? extends com.tokbox.tumor.proto.OtspCore.OtspNodeAddressOrBuilder> 
        getAddressesOrBuilderList();
    com.tokbox.tumor.proto.OtspCore.OtspNodeAddressOrBuilder getAddressesOrBuilder(
        int index);
  }
  public static final class GroupManagement extends
      com.google.protobuf.GeneratedMessage
      implements GroupManagementOrBuilder {
    // Use GroupManagement.newBuilder() to construct.
    private GroupManagement(Builder builder) {
      super(builder);
    }
    private GroupManagement(boolean noInit) {}
    
    private static final GroupManagement defaultInstance;
    public static GroupManagement getDefaultInstance() {
      return defaultInstance;
    }
    
    public GroupManagement getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tokbox.tumor.proto.OtspRouting.internal_static_otsp_GroupManagement_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tokbox.tumor.proto.OtspRouting.internal_static_otsp_GroupManagement_fieldAccessorTable;
    }
    
    public enum OpCode
        implements com.google.protobuf.ProtocolMessageEnum {
      QUERY(0, 1),
      REPORT(1, 2),
      LEAVE(2, 3),
      ;
      
      public static final int QUERY_VALUE = 1;
      public static final int REPORT_VALUE = 2;
      public static final int LEAVE_VALUE = 3;
      
      
      public final int getNumber() { return value; }
      
      public static OpCode valueOf(int value) {
        switch (value) {
          case 1: return QUERY;
          case 2: return REPORT;
          case 3: return LEAVE;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<OpCode>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<OpCode>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<OpCode>() {
              public OpCode findValueByNumber(int number) {
                return OpCode.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.tokbox.tumor.proto.OtspRouting.GroupManagement.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final OpCode[] VALUES = {
        QUERY, REPORT, LEAVE, 
      };
      
      public static OpCode valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private OpCode(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:otsp.GroupManagement.OpCode)
    }
    
    private int bitField0_;
    // required .otsp.GroupManagement.OpCode opcode = 1;
    public static final int OPCODE_FIELD_NUMBER = 1;
    private com.tokbox.tumor.proto.OtspRouting.GroupManagement.OpCode opcode_;
    public boolean hasOpcode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.tokbox.tumor.proto.OtspRouting.GroupManagement.OpCode getOpcode() {
      return opcode_;
    }
    
    // repeated .otsp.OtspNodeAddress addresses = 2;
    public static final int ADDRESSES_FIELD_NUMBER = 2;
    private java.util.List<com.tokbox.tumor.proto.OtspCore.OtspNodeAddress> addresses_;
    public java.util.List<com.tokbox.tumor.proto.OtspCore.OtspNodeAddress> getAddressesList() {
      return addresses_;
    }
    public java.util.List<? extends com.tokbox.tumor.proto.OtspCore.OtspNodeAddressOrBuilder> 
        getAddressesOrBuilderList() {
      return addresses_;
    }
    public int getAddressesCount() {
      return addresses_.size();
    }
    public com.tokbox.tumor.proto.OtspCore.OtspNodeAddress getAddresses(int index) {
      return addresses_.get(index);
    }
    public com.tokbox.tumor.proto.OtspCore.OtspNodeAddressOrBuilder getAddressesOrBuilder(
        int index) {
      return addresses_.get(index);
    }
    
    private void initFields() {
      opcode_ = com.tokbox.tumor.proto.OtspRouting.GroupManagement.OpCode.QUERY;
      addresses_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasOpcode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getAddressesCount(); i++) {
        if (!getAddresses(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, opcode_.getNumber());
      }
      for (int i = 0; i < addresses_.size(); i++) {
        output.writeMessage(2, addresses_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, opcode_.getNumber());
      }
      for (int i = 0; i < addresses_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, addresses_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.tokbox.tumor.proto.OtspRouting.GroupManagement parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspRouting.GroupManagement parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspRouting.GroupManagement parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspRouting.GroupManagement parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspRouting.GroupManagement parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspRouting.GroupManagement parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspRouting.GroupManagement parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.tokbox.tumor.proto.OtspRouting.GroupManagement parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.tokbox.tumor.proto.OtspRouting.GroupManagement parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspRouting.GroupManagement parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.tokbox.tumor.proto.OtspRouting.GroupManagement prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.tokbox.tumor.proto.OtspRouting.GroupManagementOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tokbox.tumor.proto.OtspRouting.internal_static_otsp_GroupManagement_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tokbox.tumor.proto.OtspRouting.internal_static_otsp_GroupManagement_fieldAccessorTable;
      }
      
      // Construct using com.tokbox.tumor.proto.OtspRouting.GroupManagement.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAddressesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        opcode_ = com.tokbox.tumor.proto.OtspRouting.GroupManagement.OpCode.QUERY;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (addressesBuilder_ == null) {
          addresses_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          addressesBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tokbox.tumor.proto.OtspRouting.GroupManagement.getDescriptor();
      }
      
      public com.tokbox.tumor.proto.OtspRouting.GroupManagement getDefaultInstanceForType() {
        return com.tokbox.tumor.proto.OtspRouting.GroupManagement.getDefaultInstance();
      }
      
      public com.tokbox.tumor.proto.OtspRouting.GroupManagement build() {
        com.tokbox.tumor.proto.OtspRouting.GroupManagement result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.tokbox.tumor.proto.OtspRouting.GroupManagement buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.tokbox.tumor.proto.OtspRouting.GroupManagement result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.tokbox.tumor.proto.OtspRouting.GroupManagement buildPartial() {
        com.tokbox.tumor.proto.OtspRouting.GroupManagement result = new com.tokbox.tumor.proto.OtspRouting.GroupManagement(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.opcode_ = opcode_;
        if (addressesBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            addresses_ = java.util.Collections.unmodifiableList(addresses_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.addresses_ = addresses_;
        } else {
          result.addresses_ = addressesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tokbox.tumor.proto.OtspRouting.GroupManagement) {
          return mergeFrom((com.tokbox.tumor.proto.OtspRouting.GroupManagement)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.tokbox.tumor.proto.OtspRouting.GroupManagement other) {
        if (other == com.tokbox.tumor.proto.OtspRouting.GroupManagement.getDefaultInstance()) return this;
        if (other.hasOpcode()) {
          setOpcode(other.getOpcode());
        }
        if (addressesBuilder_ == null) {
          if (!other.addresses_.isEmpty()) {
            if (addresses_.isEmpty()) {
              addresses_ = other.addresses_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureAddressesIsMutable();
              addresses_.addAll(other.addresses_);
            }
            onChanged();
          }
        } else {
          if (!other.addresses_.isEmpty()) {
            if (addressesBuilder_.isEmpty()) {
              addressesBuilder_.dispose();
              addressesBuilder_ = null;
              addresses_ = other.addresses_;
              bitField0_ = (bitField0_ & ~0x00000002);
              addressesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAddressesFieldBuilder() : null;
            } else {
              addressesBuilder_.addAllMessages(other.addresses_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasOpcode()) {
          
          return false;
        }
        for (int i = 0; i < getAddressesCount(); i++) {
          if (!getAddresses(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.tokbox.tumor.proto.OtspRouting.GroupManagement.OpCode value = com.tokbox.tumor.proto.OtspRouting.GroupManagement.OpCode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                opcode_ = value;
              }
              break;
            }
            case 18: {
              com.tokbox.tumor.proto.OtspCore.OtspNodeAddress.Builder subBuilder = com.tokbox.tumor.proto.OtspCore.OtspNodeAddress.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addAddresses(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .otsp.GroupManagement.OpCode opcode = 1;
      private com.tokbox.tumor.proto.OtspRouting.GroupManagement.OpCode opcode_ = com.tokbox.tumor.proto.OtspRouting.GroupManagement.OpCode.QUERY;
      public boolean hasOpcode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.tokbox.tumor.proto.OtspRouting.GroupManagement.OpCode getOpcode() {
        return opcode_;
      }
      public Builder setOpcode(com.tokbox.tumor.proto.OtspRouting.GroupManagement.OpCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        opcode_ = value;
        onChanged();
        return this;
      }
      public Builder clearOpcode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        opcode_ = com.tokbox.tumor.proto.OtspRouting.GroupManagement.OpCode.QUERY;
        onChanged();
        return this;
      }
      
      // repeated .otsp.OtspNodeAddress addresses = 2;
      private java.util.List<com.tokbox.tumor.proto.OtspCore.OtspNodeAddress> addresses_ =
        java.util.Collections.emptyList();
      private void ensureAddressesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          addresses_ = new java.util.ArrayList<com.tokbox.tumor.proto.OtspCore.OtspNodeAddress>(addresses_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.tokbox.tumor.proto.OtspCore.OtspNodeAddress, com.tokbox.tumor.proto.OtspCore.OtspNodeAddress.Builder, com.tokbox.tumor.proto.OtspCore.OtspNodeAddressOrBuilder> addressesBuilder_;
      
      public java.util.List<com.tokbox.tumor.proto.OtspCore.OtspNodeAddress> getAddressesList() {
        if (addressesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(addresses_);
        } else {
          return addressesBuilder_.getMessageList();
        }
      }
      public int getAddressesCount() {
        if (addressesBuilder_ == null) {
          return addresses_.size();
        } else {
          return addressesBuilder_.getCount();
        }
      }
      public com.tokbox.tumor.proto.OtspCore.OtspNodeAddress getAddresses(int index) {
        if (addressesBuilder_ == null) {
          return addresses_.get(index);
        } else {
          return addressesBuilder_.getMessage(index);
        }
      }
      public Builder setAddresses(
          int index, com.tokbox.tumor.proto.OtspCore.OtspNodeAddress value) {
        if (addressesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddressesIsMutable();
          addresses_.set(index, value);
          onChanged();
        } else {
          addressesBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setAddresses(
          int index, com.tokbox.tumor.proto.OtspCore.OtspNodeAddress.Builder builderForValue) {
        if (addressesBuilder_ == null) {
          ensureAddressesIsMutable();
          addresses_.set(index, builderForValue.build());
          onChanged();
        } else {
          addressesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAddresses(com.tokbox.tumor.proto.OtspCore.OtspNodeAddress value) {
        if (addressesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddressesIsMutable();
          addresses_.add(value);
          onChanged();
        } else {
          addressesBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addAddresses(
          int index, com.tokbox.tumor.proto.OtspCore.OtspNodeAddress value) {
        if (addressesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddressesIsMutable();
          addresses_.add(index, value);
          onChanged();
        } else {
          addressesBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addAddresses(
          com.tokbox.tumor.proto.OtspCore.OtspNodeAddress.Builder builderForValue) {
        if (addressesBuilder_ == null) {
          ensureAddressesIsMutable();
          addresses_.add(builderForValue.build());
          onChanged();
        } else {
          addressesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addAddresses(
          int index, com.tokbox.tumor.proto.OtspCore.OtspNodeAddress.Builder builderForValue) {
        if (addressesBuilder_ == null) {
          ensureAddressesIsMutable();
          addresses_.add(index, builderForValue.build());
          onChanged();
        } else {
          addressesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllAddresses(
          java.lang.Iterable<? extends com.tokbox.tumor.proto.OtspCore.OtspNodeAddress> values) {
        if (addressesBuilder_ == null) {
          ensureAddressesIsMutable();
          super.addAll(values, addresses_);
          onChanged();
        } else {
          addressesBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearAddresses() {
        if (addressesBuilder_ == null) {
          addresses_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          addressesBuilder_.clear();
        }
        return this;
      }
      public Builder removeAddresses(int index) {
        if (addressesBuilder_ == null) {
          ensureAddressesIsMutable();
          addresses_.remove(index);
          onChanged();
        } else {
          addressesBuilder_.remove(index);
        }
        return this;
      }
      public com.tokbox.tumor.proto.OtspCore.OtspNodeAddress.Builder getAddressesBuilder(
          int index) {
        return getAddressesFieldBuilder().getBuilder(index);
      }
      public com.tokbox.tumor.proto.OtspCore.OtspNodeAddressOrBuilder getAddressesOrBuilder(
          int index) {
        if (addressesBuilder_ == null) {
          return addresses_.get(index);  } else {
          return addressesBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.tokbox.tumor.proto.OtspCore.OtspNodeAddressOrBuilder> 
           getAddressesOrBuilderList() {
        if (addressesBuilder_ != null) {
          return addressesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(addresses_);
        }
      }
      public com.tokbox.tumor.proto.OtspCore.OtspNodeAddress.Builder addAddressesBuilder() {
        return getAddressesFieldBuilder().addBuilder(
            com.tokbox.tumor.proto.OtspCore.OtspNodeAddress.getDefaultInstance());
      }
      public com.tokbox.tumor.proto.OtspCore.OtspNodeAddress.Builder addAddressesBuilder(
          int index) {
        return getAddressesFieldBuilder().addBuilder(
            index, com.tokbox.tumor.proto.OtspCore.OtspNodeAddress.getDefaultInstance());
      }
      public java.util.List<com.tokbox.tumor.proto.OtspCore.OtspNodeAddress.Builder> 
           getAddressesBuilderList() {
        return getAddressesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.tokbox.tumor.proto.OtspCore.OtspNodeAddress, com.tokbox.tumor.proto.OtspCore.OtspNodeAddress.Builder, com.tokbox.tumor.proto.OtspCore.OtspNodeAddressOrBuilder> 
          getAddressesFieldBuilder() {
        if (addressesBuilder_ == null) {
          addressesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.tokbox.tumor.proto.OtspCore.OtspNodeAddress, com.tokbox.tumor.proto.OtspCore.OtspNodeAddress.Builder, com.tokbox.tumor.proto.OtspCore.OtspNodeAddressOrBuilder>(
                  addresses_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          addresses_ = null;
        }
        return addressesBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:otsp.GroupManagement)
    }
    
    static {
      defaultInstance = new GroupManagement(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:otsp.GroupManagement)
  }
  
  public interface ControlManagementOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .otsp.ControlManagement.Type type = 1;
    boolean hasType();
    com.tokbox.tumor.proto.OtspRouting.ControlManagement.Type getType();
    
    // optional .otsp.ControlManagement.Code code = 2;
    boolean hasCode();
    com.tokbox.tumor.proto.OtspRouting.ControlManagement.Code getCode();
  }
  public static final class ControlManagement extends
      com.google.protobuf.GeneratedMessage
      implements ControlManagementOrBuilder {
    // Use ControlManagement.newBuilder() to construct.
    private ControlManagement(Builder builder) {
      super(builder);
    }
    private ControlManagement(boolean noInit) {}
    
    private static final ControlManagement defaultInstance;
    public static ControlManagement getDefaultInstance() {
      return defaultInstance;
    }
    
    public ControlManagement getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tokbox.tumor.proto.OtspRouting.internal_static_otsp_ControlManagement_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tokbox.tumor.proto.OtspRouting.internal_static_otsp_ControlManagement_fieldAccessorTable;
    }
    
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      ECHO_REPLY(0, 0),
      DESTINATION_UNREACHABLE(1, 3),
      ECHO_REQUEST(2, 8),
      PARAMETER_PROBLEM(3, 12),
      ;
      
      public static final int ECHO_REPLY_VALUE = 0;
      public static final int DESTINATION_UNREACHABLE_VALUE = 3;
      public static final int ECHO_REQUEST_VALUE = 8;
      public static final int PARAMETER_PROBLEM_VALUE = 12;
      
      
      public final int getNumber() { return value; }
      
      public static Type valueOf(int value) {
        switch (value) {
          case 0: return ECHO_REPLY;
          case 3: return DESTINATION_UNREACHABLE;
          case 8: return ECHO_REQUEST;
          case 12: return PARAMETER_PROBLEM;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.tokbox.tumor.proto.OtspRouting.ControlManagement.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Type[] VALUES = {
        ECHO_REPLY, DESTINATION_UNREACHABLE, ECHO_REQUEST, PARAMETER_PROBLEM, 
      };
      
      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:otsp.ControlManagement.Type)
    }
    
    public enum Code
        implements com.google.protobuf.ProtocolMessageEnum {
      NETWORK_UNREACHABLE(0, 30),
      NODE_UNREACHABLE(1, 31),
      SOURCE_NODE_ISOLATED(2, 38),
      SOURCE_SIGNATURE_FAILED(3, 123),
      ;
      
      public static final int NETWORK_UNREACHABLE_VALUE = 30;
      public static final int NODE_UNREACHABLE_VALUE = 31;
      public static final int SOURCE_NODE_ISOLATED_VALUE = 38;
      public static final int SOURCE_SIGNATURE_FAILED_VALUE = 123;
      
      
      public final int getNumber() { return value; }
      
      public static Code valueOf(int value) {
        switch (value) {
          case 30: return NETWORK_UNREACHABLE;
          case 31: return NODE_UNREACHABLE;
          case 38: return SOURCE_NODE_ISOLATED;
          case 123: return SOURCE_SIGNATURE_FAILED;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Code>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Code>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Code>() {
              public Code findValueByNumber(int number) {
                return Code.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.tokbox.tumor.proto.OtspRouting.ControlManagement.getDescriptor().getEnumTypes().get(1);
      }
      
      private static final Code[] VALUES = {
        NETWORK_UNREACHABLE, NODE_UNREACHABLE, SOURCE_NODE_ISOLATED, SOURCE_SIGNATURE_FAILED, 
      };
      
      public static Code valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Code(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:otsp.ControlManagement.Code)
    }
    
    private int bitField0_;
    // required .otsp.ControlManagement.Type type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.tokbox.tumor.proto.OtspRouting.ControlManagement.Type type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.tokbox.tumor.proto.OtspRouting.ControlManagement.Type getType() {
      return type_;
    }
    
    // optional .otsp.ControlManagement.Code code = 2;
    public static final int CODE_FIELD_NUMBER = 2;
    private com.tokbox.tumor.proto.OtspRouting.ControlManagement.Code code_;
    public boolean hasCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.tokbox.tumor.proto.OtspRouting.ControlManagement.Code getCode() {
      return code_;
    }
    
    private void initFields() {
      type_ = com.tokbox.tumor.proto.OtspRouting.ControlManagement.Type.ECHO_REPLY;
      code_ = com.tokbox.tumor.proto.OtspRouting.ControlManagement.Code.NETWORK_UNREACHABLE;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, code_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, code_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.tokbox.tumor.proto.OtspRouting.ControlManagement parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspRouting.ControlManagement parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspRouting.ControlManagement parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspRouting.ControlManagement parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspRouting.ControlManagement parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspRouting.ControlManagement parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspRouting.ControlManagement parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.tokbox.tumor.proto.OtspRouting.ControlManagement parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.tokbox.tumor.proto.OtspRouting.ControlManagement parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspRouting.ControlManagement parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.tokbox.tumor.proto.OtspRouting.ControlManagement prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.tokbox.tumor.proto.OtspRouting.ControlManagementOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tokbox.tumor.proto.OtspRouting.internal_static_otsp_ControlManagement_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tokbox.tumor.proto.OtspRouting.internal_static_otsp_ControlManagement_fieldAccessorTable;
      }
      
      // Construct using com.tokbox.tumor.proto.OtspRouting.ControlManagement.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        type_ = com.tokbox.tumor.proto.OtspRouting.ControlManagement.Type.ECHO_REPLY;
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = com.tokbox.tumor.proto.OtspRouting.ControlManagement.Code.NETWORK_UNREACHABLE;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tokbox.tumor.proto.OtspRouting.ControlManagement.getDescriptor();
      }
      
      public com.tokbox.tumor.proto.OtspRouting.ControlManagement getDefaultInstanceForType() {
        return com.tokbox.tumor.proto.OtspRouting.ControlManagement.getDefaultInstance();
      }
      
      public com.tokbox.tumor.proto.OtspRouting.ControlManagement build() {
        com.tokbox.tumor.proto.OtspRouting.ControlManagement result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.tokbox.tumor.proto.OtspRouting.ControlManagement buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.tokbox.tumor.proto.OtspRouting.ControlManagement result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.tokbox.tumor.proto.OtspRouting.ControlManagement buildPartial() {
        com.tokbox.tumor.proto.OtspRouting.ControlManagement result = new com.tokbox.tumor.proto.OtspRouting.ControlManagement(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.code_ = code_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tokbox.tumor.proto.OtspRouting.ControlManagement) {
          return mergeFrom((com.tokbox.tumor.proto.OtspRouting.ControlManagement)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.tokbox.tumor.proto.OtspRouting.ControlManagement other) {
        if (other == com.tokbox.tumor.proto.OtspRouting.ControlManagement.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.tokbox.tumor.proto.OtspRouting.ControlManagement.Type value = com.tokbox.tumor.proto.OtspRouting.ControlManagement.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.tokbox.tumor.proto.OtspRouting.ControlManagement.Code value = com.tokbox.tumor.proto.OtspRouting.ControlManagement.Code.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                code_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .otsp.ControlManagement.Type type = 1;
      private com.tokbox.tumor.proto.OtspRouting.ControlManagement.Type type_ = com.tokbox.tumor.proto.OtspRouting.ControlManagement.Type.ECHO_REPLY;
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.tokbox.tumor.proto.OtspRouting.ControlManagement.Type getType() {
        return type_;
      }
      public Builder setType(com.tokbox.tumor.proto.OtspRouting.ControlManagement.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.tokbox.tumor.proto.OtspRouting.ControlManagement.Type.ECHO_REPLY;
        onChanged();
        return this;
      }
      
      // optional .otsp.ControlManagement.Code code = 2;
      private com.tokbox.tumor.proto.OtspRouting.ControlManagement.Code code_ = com.tokbox.tumor.proto.OtspRouting.ControlManagement.Code.NETWORK_UNREACHABLE;
      public boolean hasCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.tokbox.tumor.proto.OtspRouting.ControlManagement.Code getCode() {
        return code_;
      }
      public Builder setCode(com.tokbox.tumor.proto.OtspRouting.ControlManagement.Code value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        code_ = value;
        onChanged();
        return this;
      }
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        code_ = com.tokbox.tumor.proto.OtspRouting.ControlManagement.Code.NETWORK_UNREACHABLE;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:otsp.ControlManagement)
    }
    
    static {
      defaultInstance = new ControlManagement(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:otsp.ControlManagement)
  }
  
  public interface ConnectionManagementOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .otsp.ConnectionManagement.OpCode opcode = 1;
    boolean hasOpcode();
    com.tokbox.tumor.proto.OtspRouting.ConnectionManagement.OpCode getOpcode();
    
    // optional bytes dhprime = 2;
    boolean hasDhprime();
    com.google.protobuf.ByteString getDhprime();
    
    // optional bytes dhbase = 3;
    boolean hasDhbase();
    com.google.protobuf.ByteString getDhbase();
    
    // optional bytes dhpublic = 4;
    boolean hasDhpublic();
    com.google.protobuf.ByteString getDhpublic();
  }
  public static final class ConnectionManagement extends
      com.google.protobuf.GeneratedMessage
      implements ConnectionManagementOrBuilder {
    // Use ConnectionManagement.newBuilder() to construct.
    private ConnectionManagement(Builder builder) {
      super(builder);
    }
    private ConnectionManagement(boolean noInit) {}
    
    private static final ConnectionManagement defaultInstance;
    public static ConnectionManagement getDefaultInstance() {
      return defaultInstance;
    }
    
    public ConnectionManagement getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tokbox.tumor.proto.OtspRouting.internal_static_otsp_ConnectionManagement_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tokbox.tumor.proto.OtspRouting.internal_static_otsp_ConnectionManagement_fieldAccessorTable;
    }
    
    public enum OpCode
        implements com.google.protobuf.ProtocolMessageEnum {
      CONNECT(0, 1),
      KEEPALIVE(1, 2),
      BYE(2, 3),
      ;
      
      public static final int CONNECT_VALUE = 1;
      public static final int KEEPALIVE_VALUE = 2;
      public static final int BYE_VALUE = 3;
      
      
      public final int getNumber() { return value; }
      
      public static OpCode valueOf(int value) {
        switch (value) {
          case 1: return CONNECT;
          case 2: return KEEPALIVE;
          case 3: return BYE;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<OpCode>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<OpCode>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<OpCode>() {
              public OpCode findValueByNumber(int number) {
                return OpCode.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.tokbox.tumor.proto.OtspRouting.ConnectionManagement.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final OpCode[] VALUES = {
        CONNECT, KEEPALIVE, BYE, 
      };
      
      public static OpCode valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private OpCode(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:otsp.ConnectionManagement.OpCode)
    }
    
    private int bitField0_;
    // required .otsp.ConnectionManagement.OpCode opcode = 1;
    public static final int OPCODE_FIELD_NUMBER = 1;
    private com.tokbox.tumor.proto.OtspRouting.ConnectionManagement.OpCode opcode_;
    public boolean hasOpcode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.tokbox.tumor.proto.OtspRouting.ConnectionManagement.OpCode getOpcode() {
      return opcode_;
    }
    
    // optional bytes dhprime = 2;
    public static final int DHPRIME_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString dhprime_;
    public boolean hasDhprime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.google.protobuf.ByteString getDhprime() {
      return dhprime_;
    }
    
    // optional bytes dhbase = 3;
    public static final int DHBASE_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString dhbase_;
    public boolean hasDhbase() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public com.google.protobuf.ByteString getDhbase() {
      return dhbase_;
    }
    
    // optional bytes dhpublic = 4;
    public static final int DHPUBLIC_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString dhpublic_;
    public boolean hasDhpublic() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public com.google.protobuf.ByteString getDhpublic() {
      return dhpublic_;
    }
    
    private void initFields() {
      opcode_ = com.tokbox.tumor.proto.OtspRouting.ConnectionManagement.OpCode.CONNECT;
      dhprime_ = com.google.protobuf.ByteString.EMPTY;
      dhbase_ = com.google.protobuf.ByteString.EMPTY;
      dhpublic_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasOpcode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, opcode_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, dhprime_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, dhbase_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, dhpublic_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, opcode_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, dhprime_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, dhbase_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, dhpublic_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.tokbox.tumor.proto.OtspRouting.ConnectionManagement parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspRouting.ConnectionManagement parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspRouting.ConnectionManagement parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspRouting.ConnectionManagement parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspRouting.ConnectionManagement parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspRouting.ConnectionManagement parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspRouting.ConnectionManagement parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.tokbox.tumor.proto.OtspRouting.ConnectionManagement parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.tokbox.tumor.proto.OtspRouting.ConnectionManagement parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspRouting.ConnectionManagement parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.tokbox.tumor.proto.OtspRouting.ConnectionManagement prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.tokbox.tumor.proto.OtspRouting.ConnectionManagementOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tokbox.tumor.proto.OtspRouting.internal_static_otsp_ConnectionManagement_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tokbox.tumor.proto.OtspRouting.internal_static_otsp_ConnectionManagement_fieldAccessorTable;
      }
      
      // Construct using com.tokbox.tumor.proto.OtspRouting.ConnectionManagement.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        opcode_ = com.tokbox.tumor.proto.OtspRouting.ConnectionManagement.OpCode.CONNECT;
        bitField0_ = (bitField0_ & ~0x00000001);
        dhprime_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        dhbase_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        dhpublic_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tokbox.tumor.proto.OtspRouting.ConnectionManagement.getDescriptor();
      }
      
      public com.tokbox.tumor.proto.OtspRouting.ConnectionManagement getDefaultInstanceForType() {
        return com.tokbox.tumor.proto.OtspRouting.ConnectionManagement.getDefaultInstance();
      }
      
      public com.tokbox.tumor.proto.OtspRouting.ConnectionManagement build() {
        com.tokbox.tumor.proto.OtspRouting.ConnectionManagement result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.tokbox.tumor.proto.OtspRouting.ConnectionManagement buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.tokbox.tumor.proto.OtspRouting.ConnectionManagement result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.tokbox.tumor.proto.OtspRouting.ConnectionManagement buildPartial() {
        com.tokbox.tumor.proto.OtspRouting.ConnectionManagement result = new com.tokbox.tumor.proto.OtspRouting.ConnectionManagement(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.opcode_ = opcode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.dhprime_ = dhprime_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.dhbase_ = dhbase_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.dhpublic_ = dhpublic_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tokbox.tumor.proto.OtspRouting.ConnectionManagement) {
          return mergeFrom((com.tokbox.tumor.proto.OtspRouting.ConnectionManagement)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.tokbox.tumor.proto.OtspRouting.ConnectionManagement other) {
        if (other == com.tokbox.tumor.proto.OtspRouting.ConnectionManagement.getDefaultInstance()) return this;
        if (other.hasOpcode()) {
          setOpcode(other.getOpcode());
        }
        if (other.hasDhprime()) {
          setDhprime(other.getDhprime());
        }
        if (other.hasDhbase()) {
          setDhbase(other.getDhbase());
        }
        if (other.hasDhpublic()) {
          setDhpublic(other.getDhpublic());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasOpcode()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.tokbox.tumor.proto.OtspRouting.ConnectionManagement.OpCode value = com.tokbox.tumor.proto.OtspRouting.ConnectionManagement.OpCode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                opcode_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              dhprime_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              dhbase_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              dhpublic_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .otsp.ConnectionManagement.OpCode opcode = 1;
      private com.tokbox.tumor.proto.OtspRouting.ConnectionManagement.OpCode opcode_ = com.tokbox.tumor.proto.OtspRouting.ConnectionManagement.OpCode.CONNECT;
      public boolean hasOpcode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.tokbox.tumor.proto.OtspRouting.ConnectionManagement.OpCode getOpcode() {
        return opcode_;
      }
      public Builder setOpcode(com.tokbox.tumor.proto.OtspRouting.ConnectionManagement.OpCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        opcode_ = value;
        onChanged();
        return this;
      }
      public Builder clearOpcode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        opcode_ = com.tokbox.tumor.proto.OtspRouting.ConnectionManagement.OpCode.CONNECT;
        onChanged();
        return this;
      }
      
      // optional bytes dhprime = 2;
      private com.google.protobuf.ByteString dhprime_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasDhprime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.google.protobuf.ByteString getDhprime() {
        return dhprime_;
      }
      public Builder setDhprime(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        dhprime_ = value;
        onChanged();
        return this;
      }
      public Builder clearDhprime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        dhprime_ = getDefaultInstance().getDhprime();
        onChanged();
        return this;
      }
      
      // optional bytes dhbase = 3;
      private com.google.protobuf.ByteString dhbase_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasDhbase() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public com.google.protobuf.ByteString getDhbase() {
        return dhbase_;
      }
      public Builder setDhbase(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        dhbase_ = value;
        onChanged();
        return this;
      }
      public Builder clearDhbase() {
        bitField0_ = (bitField0_ & ~0x00000004);
        dhbase_ = getDefaultInstance().getDhbase();
        onChanged();
        return this;
      }
      
      // optional bytes dhpublic = 4;
      private com.google.protobuf.ByteString dhpublic_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasDhpublic() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public com.google.protobuf.ByteString getDhpublic() {
        return dhpublic_;
      }
      public Builder setDhpublic(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        dhpublic_ = value;
        onChanged();
        return this;
      }
      public Builder clearDhpublic() {
        bitField0_ = (bitField0_ & ~0x00000008);
        dhpublic_ = getDefaultInstance().getDhpublic();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:otsp.ConnectionManagement)
    }
    
    static {
      defaultInstance = new ConnectionManagement(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:otsp.ConnectionManagement)
  }
  
  public interface SignatureOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional bytes challenge = 1;
    boolean hasChallenge();
    com.google.protobuf.ByteString getChallenge();
    
    // optional bytes signature = 2;
    boolean hasSignature();
    com.google.protobuf.ByteString getSignature();
  }
  public static final class Signature extends
      com.google.protobuf.GeneratedMessage
      implements SignatureOrBuilder {
    // Use Signature.newBuilder() to construct.
    private Signature(Builder builder) {
      super(builder);
    }
    private Signature(boolean noInit) {}
    
    private static final Signature defaultInstance;
    public static Signature getDefaultInstance() {
      return defaultInstance;
    }
    
    public Signature getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tokbox.tumor.proto.OtspRouting.internal_static_otsp_Signature_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tokbox.tumor.proto.OtspRouting.internal_static_otsp_Signature_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional bytes challenge = 1;
    public static final int CHALLENGE_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString challenge_;
    public boolean hasChallenge() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.google.protobuf.ByteString getChallenge() {
      return challenge_;
    }
    
    // optional bytes signature = 2;
    public static final int SIGNATURE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString signature_;
    public boolean hasSignature() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.google.protobuf.ByteString getSignature() {
      return signature_;
    }
    
    private void initFields() {
      challenge_ = com.google.protobuf.ByteString.EMPTY;
      signature_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, challenge_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, signature_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, challenge_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, signature_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.tokbox.tumor.proto.OtspRouting.Signature parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspRouting.Signature parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspRouting.Signature parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspRouting.Signature parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspRouting.Signature parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspRouting.Signature parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspRouting.Signature parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.tokbox.tumor.proto.OtspRouting.Signature parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.tokbox.tumor.proto.OtspRouting.Signature parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspRouting.Signature parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.tokbox.tumor.proto.OtspRouting.Signature prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.tokbox.tumor.proto.OtspRouting.SignatureOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tokbox.tumor.proto.OtspRouting.internal_static_otsp_Signature_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tokbox.tumor.proto.OtspRouting.internal_static_otsp_Signature_fieldAccessorTable;
      }
      
      // Construct using com.tokbox.tumor.proto.OtspRouting.Signature.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        challenge_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        signature_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tokbox.tumor.proto.OtspRouting.Signature.getDescriptor();
      }
      
      public com.tokbox.tumor.proto.OtspRouting.Signature getDefaultInstanceForType() {
        return com.tokbox.tumor.proto.OtspRouting.Signature.getDefaultInstance();
      }
      
      public com.tokbox.tumor.proto.OtspRouting.Signature build() {
        com.tokbox.tumor.proto.OtspRouting.Signature result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.tokbox.tumor.proto.OtspRouting.Signature buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.tokbox.tumor.proto.OtspRouting.Signature result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.tokbox.tumor.proto.OtspRouting.Signature buildPartial() {
        com.tokbox.tumor.proto.OtspRouting.Signature result = new com.tokbox.tumor.proto.OtspRouting.Signature(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.challenge_ = challenge_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.signature_ = signature_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tokbox.tumor.proto.OtspRouting.Signature) {
          return mergeFrom((com.tokbox.tumor.proto.OtspRouting.Signature)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.tokbox.tumor.proto.OtspRouting.Signature other) {
        if (other == com.tokbox.tumor.proto.OtspRouting.Signature.getDefaultInstance()) return this;
        if (other.hasChallenge()) {
          setChallenge(other.getChallenge());
        }
        if (other.hasSignature()) {
          setSignature(other.getSignature());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              challenge_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              signature_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional bytes challenge = 1;
      private com.google.protobuf.ByteString challenge_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasChallenge() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.google.protobuf.ByteString getChallenge() {
        return challenge_;
      }
      public Builder setChallenge(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        challenge_ = value;
        onChanged();
        return this;
      }
      public Builder clearChallenge() {
        bitField0_ = (bitField0_ & ~0x00000001);
        challenge_ = getDefaultInstance().getChallenge();
        onChanged();
        return this;
      }
      
      // optional bytes signature = 2;
      private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasSignature() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.google.protobuf.ByteString getSignature() {
        return signature_;
      }
      public Builder setSignature(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        signature_ = value;
        onChanged();
        return this;
      }
      public Builder clearSignature() {
        bitField0_ = (bitField0_ & ~0x00000002);
        signature_ = getDefaultInstance().getSignature();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:otsp.Signature)
    }
    
    static {
      defaultInstance = new Signature(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:otsp.Signature)
  }
  
  public static final int GROUPMANAGEMENT_FIELD_NUMBER = 10;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.tokbox.tumor.proto.OtspCore.OtspMessage,
      com.tokbox.tumor.proto.OtspRouting.GroupManagement> groupManagement = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.tokbox.tumor.proto.OtspRouting.GroupManagement.class,
        com.tokbox.tumor.proto.OtspRouting.GroupManagement.getDefaultInstance());
  public static final int CONTROLMANAGEMENT_FIELD_NUMBER = 11;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.tokbox.tumor.proto.OtspCore.OtspMessage,
      com.tokbox.tumor.proto.OtspRouting.ControlManagement> controlManagement = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.tokbox.tumor.proto.OtspRouting.ControlManagement.class,
        com.tokbox.tumor.proto.OtspRouting.ControlManagement.getDefaultInstance());
  public static final int CONNECTIONMANAGEMENT_FIELD_NUMBER = 12;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.tokbox.tumor.proto.OtspCore.OtspMessage,
      com.tokbox.tumor.proto.OtspRouting.ConnectionManagement> connectionManagement = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.tokbox.tumor.proto.OtspRouting.ConnectionManagement.class,
        com.tokbox.tumor.proto.OtspRouting.ConnectionManagement.getDefaultInstance());
  public static final int SIGNATURE_FIELD_NUMBER = 13;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.tokbox.tumor.proto.OtspCore.OtspMessage,
      com.tokbox.tumor.proto.OtspRouting.Signature> signature = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.tokbox.tumor.proto.OtspRouting.Signature.class,
        com.tokbox.tumor.proto.OtspRouting.Signature.getDefaultInstance());
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_otsp_GroupManagement_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_otsp_GroupManagement_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_otsp_ControlManagement_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_otsp_ControlManagement_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_otsp_ConnectionManagement_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_otsp_ConnectionManagement_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_otsp_Signature_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_otsp_Signature_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\0232otsp_routing.proto\022\004otsp\032\0201otsp_root." +
      "proto\"\225\001\n\017GroupManagement\022,\n\006opcode\030\001 \002(" +
      "\0162\034.otsp.GroupManagement.OpCode\022(\n\taddre" +
      "sses\030\002 \003(\0132\025.otsp.OtspNodeAddress\"*\n\006OpC" +
      "ode\022\t\n\005QUERY\020\001\022\n\n\006REPORT\020\002\022\t\n\005LEAVE\020\003\"\267\002" +
      "\n\021ControlManagement\022*\n\004type\030\001 \002(\0162\034.otsp" +
      ".ControlManagement.Type\022*\n\004code\030\002 \001(\0162\034." +
      "otsp.ControlManagement.Code\"\\\n\004Type\022\016\n\nE" +
      "CHO_REPLY\020\000\022\033\n\027DESTINATION_UNREACHABLE\020\003" +
      "\022\020\n\014ECHO_REQUEST\020\010\022\025\n\021PARAMETER_PROBLEM\020",
      "\014\"l\n\004Code\022\027\n\023NETWORK_UNREACHABLE\020\036\022\024\n\020NO" +
      "DE_UNREACHABLE\020\037\022\030\n\024SOURCE_NODE_ISOLATED" +
      "\020&\022\033\n\027SOURCE_SIGNATURE_FAILED\020{\"\253\001\n\024Conn" +
      "ectionManagement\0221\n\006opcode\030\001 \002(\0162!.otsp." +
      "ConnectionManagement.OpCode\022\017\n\007dhprime\030\002" +
      " \001(\014\022\016\n\006dhbase\030\003 \001(\014\022\020\n\010dhpublic\030\004 \001(\014\"-" +
      "\n\006OpCode\022\013\n\007CONNECT\020\001\022\r\n\tKEEPALIVE\020\002\022\007\n\003" +
      "BYE\020\003\"1\n\tSignature\022\021\n\tchallenge\030\001 \001(\014\022\021\n" +
      "\tsignature\030\002 \001(\014:A\n\017groupManagement\022\021.ot" +
      "sp.OtspMessage\030\n \001(\0132\025.otsp.GroupManagem",
      "ent:E\n\021controlManagement\022\021.otsp.OtspMess" +
      "age\030\013 \001(\0132\027.otsp.ControlManagement:K\n\024co" +
      "nnectionManagement\022\021.otsp.OtspMessage\030\014 " +
      "\001(\0132\032.otsp.ConnectionManagement:5\n\tsigna" +
      "ture\022\021.otsp.OtspMessage\030\r \001(\0132\017.otsp.Sig" +
      "natureB%\n\026com.tokbox.tumor.protoB\013OtspRo" +
      "uting"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_otsp_GroupManagement_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_otsp_GroupManagement_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_otsp_GroupManagement_descriptor,
              new java.lang.String[] { "Opcode", "Addresses", },
              com.tokbox.tumor.proto.OtspRouting.GroupManagement.class,
              com.tokbox.tumor.proto.OtspRouting.GroupManagement.Builder.class);
          internal_static_otsp_ControlManagement_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_otsp_ControlManagement_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_otsp_ControlManagement_descriptor,
              new java.lang.String[] { "Type", "Code", },
              com.tokbox.tumor.proto.OtspRouting.ControlManagement.class,
              com.tokbox.tumor.proto.OtspRouting.ControlManagement.Builder.class);
          internal_static_otsp_ConnectionManagement_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_otsp_ConnectionManagement_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_otsp_ConnectionManagement_descriptor,
              new java.lang.String[] { "Opcode", "Dhprime", "Dhbase", "Dhpublic", },
              com.tokbox.tumor.proto.OtspRouting.ConnectionManagement.class,
              com.tokbox.tumor.proto.OtspRouting.ConnectionManagement.Builder.class);
          internal_static_otsp_Signature_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_otsp_Signature_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_otsp_Signature_descriptor,
              new java.lang.String[] { "Challenge", "Signature", },
              com.tokbox.tumor.proto.OtspRouting.Signature.class,
              com.tokbox.tumor.proto.OtspRouting.Signature.Builder.class);
          groupManagement.internalInit(descriptor.getExtensions().get(0));
          controlManagement.internalInit(descriptor.getExtensions().get(1));
          connectionManagement.internalInit(descriptor.getExtensions().get(2));
          signature.internalInit(descriptor.getExtensions().get(3));
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.tokbox.tumor.proto.OtspCore.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
