// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 3otsp_service.proto

package com.tokbox.tumor.proto;

public final class OtspService {
  private OtspService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(com.tokbox.tumor.proto.OtspService.push);
    registry.add(com.tokbox.tumor.proto.OtspService.presence);
    registry.add(com.tokbox.tumor.proto.OtspService.iq);
    registry.add(com.tokbox.tumor.proto.OtspService.authenticate);
  }
  public interface PushOrBuilder extends
      com.google.protobuf.GeneratedMessage.
          ExtendableMessageOrBuilder<Push> {
  }
  public static final class Push extends
      com.google.protobuf.GeneratedMessage.ExtendableMessage<
        Push> implements PushOrBuilder {
    // Use Push.newBuilder() to construct.
    private Push(Builder builder) {
      super(builder);
    }
    private Push(boolean noInit) {}
    
    private static final Push defaultInstance;
    public static Push getDefaultInstance() {
      return defaultInstance;
    }
    
    public Push getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tokbox.tumor.proto.OtspService.internal_static_otsp_Push_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tokbox.tumor.proto.OtspService.internal_static_otsp_Push_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      com.google.protobuf.GeneratedMessage
        .ExtendableMessage<com.tokbox.tumor.proto.OtspService.Push>.ExtensionWriter extensionWriter =
          newExtensionWriter();
      extensionWriter.writeUntil(536870912, output);
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += extensionsSerializedSize();
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.tokbox.tumor.proto.OtspService.Push parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspService.Push parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspService.Push parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspService.Push parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspService.Push parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspService.Push parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspService.Push parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.tokbox.tumor.proto.OtspService.Push parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.tokbox.tumor.proto.OtspService.Push parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspService.Push parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.tokbox.tumor.proto.OtspService.Push prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.ExtendableBuilder<
          com.tokbox.tumor.proto.OtspService.Push, Builder> implements com.tokbox.tumor.proto.OtspService.PushOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tokbox.tumor.proto.OtspService.internal_static_otsp_Push_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tokbox.tumor.proto.OtspService.internal_static_otsp_Push_fieldAccessorTable;
      }
      
      // Construct using com.tokbox.tumor.proto.OtspService.Push.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tokbox.tumor.proto.OtspService.Push.getDescriptor();
      }
      
      public com.tokbox.tumor.proto.OtspService.Push getDefaultInstanceForType() {
        return com.tokbox.tumor.proto.OtspService.Push.getDefaultInstance();
      }
      
      public com.tokbox.tumor.proto.OtspService.Push build() {
        com.tokbox.tumor.proto.OtspService.Push result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.tokbox.tumor.proto.OtspService.Push buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.tokbox.tumor.proto.OtspService.Push result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.tokbox.tumor.proto.OtspService.Push buildPartial() {
        com.tokbox.tumor.proto.OtspService.Push result = new com.tokbox.tumor.proto.OtspService.Push(this);
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tokbox.tumor.proto.OtspService.Push) {
          return mergeFrom((com.tokbox.tumor.proto.OtspService.Push)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.tokbox.tumor.proto.OtspService.Push other) {
        if (other == com.tokbox.tumor.proto.OtspService.Push.getDefaultInstance()) return this;
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!extensionsAreInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:otsp.Push)
    }
    
    static {
      defaultInstance = new Push(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:otsp.Push)
  }
  
  public interface PresenceOrBuilder extends
      com.google.protobuf.GeneratedMessage.
          ExtendableMessageOrBuilder<Presence> {
  }
  public static final class Presence extends
      com.google.protobuf.GeneratedMessage.ExtendableMessage<
        Presence> implements PresenceOrBuilder {
    // Use Presence.newBuilder() to construct.
    private Presence(Builder builder) {
      super(builder);
    }
    private Presence(boolean noInit) {}
    
    private static final Presence defaultInstance;
    public static Presence getDefaultInstance() {
      return defaultInstance;
    }
    
    public Presence getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tokbox.tumor.proto.OtspService.internal_static_otsp_Presence_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tokbox.tumor.proto.OtspService.internal_static_otsp_Presence_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      com.google.protobuf.GeneratedMessage
        .ExtendableMessage<com.tokbox.tumor.proto.OtspService.Presence>.ExtensionWriter extensionWriter =
          newExtensionWriter();
      extensionWriter.writeUntil(100, output);
      extensionWriter.writeUntil(536870912, output);
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += extensionsSerializedSize();
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.tokbox.tumor.proto.OtspService.Presence parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspService.Presence parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspService.Presence parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspService.Presence parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspService.Presence parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspService.Presence parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspService.Presence parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.tokbox.tumor.proto.OtspService.Presence parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.tokbox.tumor.proto.OtspService.Presence parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspService.Presence parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.tokbox.tumor.proto.OtspService.Presence prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.ExtendableBuilder<
          com.tokbox.tumor.proto.OtspService.Presence, Builder> implements com.tokbox.tumor.proto.OtspService.PresenceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tokbox.tumor.proto.OtspService.internal_static_otsp_Presence_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tokbox.tumor.proto.OtspService.internal_static_otsp_Presence_fieldAccessorTable;
      }
      
      // Construct using com.tokbox.tumor.proto.OtspService.Presence.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tokbox.tumor.proto.OtspService.Presence.getDescriptor();
      }
      
      public com.tokbox.tumor.proto.OtspService.Presence getDefaultInstanceForType() {
        return com.tokbox.tumor.proto.OtspService.Presence.getDefaultInstance();
      }
      
      public com.tokbox.tumor.proto.OtspService.Presence build() {
        com.tokbox.tumor.proto.OtspService.Presence result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.tokbox.tumor.proto.OtspService.Presence buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.tokbox.tumor.proto.OtspService.Presence result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.tokbox.tumor.proto.OtspService.Presence buildPartial() {
        com.tokbox.tumor.proto.OtspService.Presence result = new com.tokbox.tumor.proto.OtspService.Presence(this);
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tokbox.tumor.proto.OtspService.Presence) {
          return mergeFrom((com.tokbox.tumor.proto.OtspService.Presence)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.tokbox.tumor.proto.OtspService.Presence other) {
        if (other == com.tokbox.tumor.proto.OtspService.Presence.getDefaultInstance()) return this;
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!extensionsAreInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:otsp.Presence)
    }
    
    static {
      defaultInstance = new Presence(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:otsp.Presence)
  }
  
  public interface IQOrBuilder extends
      com.google.protobuf.GeneratedMessage.
          ExtendableMessageOrBuilder<IQ> {
    
    // optional .otsp.IQ.Type type = 1;
    boolean hasType();
    com.tokbox.tumor.proto.OtspService.IQ.Type getType();
  }
  public static final class IQ extends
      com.google.protobuf.GeneratedMessage.ExtendableMessage<
        IQ> implements IQOrBuilder {
    // Use IQ.newBuilder() to construct.
    private IQ(Builder builder) {
      super(builder);
    }
    private IQ(boolean noInit) {}
    
    private static final IQ defaultInstance;
    public static IQ getDefaultInstance() {
      return defaultInstance;
    }
    
    public IQ getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tokbox.tumor.proto.OtspService.internal_static_otsp_IQ_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tokbox.tumor.proto.OtspService.internal_static_otsp_IQ_fieldAccessorTable;
    }
    
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      SET(0, 1),
      GET(1, 2),
      RESULT(2, 3),
      ERROR(3, 4),
      ;
      
      public static final int SET_VALUE = 1;
      public static final int GET_VALUE = 2;
      public static final int RESULT_VALUE = 3;
      public static final int ERROR_VALUE = 4;
      
      
      public final int getNumber() { return value; }
      
      public static Type valueOf(int value) {
        switch (value) {
          case 1: return SET;
          case 2: return GET;
          case 3: return RESULT;
          case 4: return ERROR;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.tokbox.tumor.proto.OtspService.IQ.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Type[] VALUES = {
        SET, GET, RESULT, ERROR, 
      };
      
      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:otsp.IQ.Type)
    }
    
    private int bitField0_;
    // optional .otsp.IQ.Type type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.tokbox.tumor.proto.OtspService.IQ.Type type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.tokbox.tumor.proto.OtspService.IQ.Type getType() {
      return type_;
    }
    
    private void initFields() {
      type_ = com.tokbox.tumor.proto.OtspService.IQ.Type.SET;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      com.google.protobuf.GeneratedMessage
        .ExtendableMessage<com.tokbox.tumor.proto.OtspService.IQ>.ExtensionWriter extensionWriter =
          newExtensionWriter();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      extensionWriter.writeUntil(536870912, output);
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      size += extensionsSerializedSize();
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.tokbox.tumor.proto.OtspService.IQ parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspService.IQ parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspService.IQ parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspService.IQ parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspService.IQ parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspService.IQ parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspService.IQ parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.tokbox.tumor.proto.OtspService.IQ parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.tokbox.tumor.proto.OtspService.IQ parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspService.IQ parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.tokbox.tumor.proto.OtspService.IQ prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.ExtendableBuilder<
          com.tokbox.tumor.proto.OtspService.IQ, Builder> implements com.tokbox.tumor.proto.OtspService.IQOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tokbox.tumor.proto.OtspService.internal_static_otsp_IQ_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tokbox.tumor.proto.OtspService.internal_static_otsp_IQ_fieldAccessorTable;
      }
      
      // Construct using com.tokbox.tumor.proto.OtspService.IQ.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        type_ = com.tokbox.tumor.proto.OtspService.IQ.Type.SET;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tokbox.tumor.proto.OtspService.IQ.getDescriptor();
      }
      
      public com.tokbox.tumor.proto.OtspService.IQ getDefaultInstanceForType() {
        return com.tokbox.tumor.proto.OtspService.IQ.getDefaultInstance();
      }
      
      public com.tokbox.tumor.proto.OtspService.IQ build() {
        com.tokbox.tumor.proto.OtspService.IQ result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.tokbox.tumor.proto.OtspService.IQ buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.tokbox.tumor.proto.OtspService.IQ result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.tokbox.tumor.proto.OtspService.IQ buildPartial() {
        com.tokbox.tumor.proto.OtspService.IQ result = new com.tokbox.tumor.proto.OtspService.IQ(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tokbox.tumor.proto.OtspService.IQ) {
          return mergeFrom((com.tokbox.tumor.proto.OtspService.IQ)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.tokbox.tumor.proto.OtspService.IQ other) {
        if (other == com.tokbox.tumor.proto.OtspService.IQ.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!extensionsAreInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.tokbox.tumor.proto.OtspService.IQ.Type value = com.tokbox.tumor.proto.OtspService.IQ.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional .otsp.IQ.Type type = 1;
      private com.tokbox.tumor.proto.OtspService.IQ.Type type_ = com.tokbox.tumor.proto.OtspService.IQ.Type.SET;
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.tokbox.tumor.proto.OtspService.IQ.Type getType() {
        return type_;
      }
      public Builder setType(com.tokbox.tumor.proto.OtspService.IQ.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.tokbox.tumor.proto.OtspService.IQ.Type.SET;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:otsp.IQ)
    }
    
    static {
      defaultInstance = new IQ(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:otsp.IQ)
  }
  
  public interface AuthenticateOrBuilder extends
      com.google.protobuf.GeneratedMessage.
          ExtendableMessageOrBuilder<Authenticate> {
    
    // optional .otsp.Authenticate.OpCode opcode = 1;
    boolean hasOpcode();
    com.tokbox.tumor.proto.OtspService.Authenticate.OpCode getOpcode();
    
    // optional string content = 2;
    boolean hasContent();
    String getContent();
  }
  public static final class Authenticate extends
      com.google.protobuf.GeneratedMessage.ExtendableMessage<
        Authenticate> implements AuthenticateOrBuilder {
    // Use Authenticate.newBuilder() to construct.
    private Authenticate(Builder builder) {
      super(builder);
    }
    private Authenticate(boolean noInit) {}
    
    private static final Authenticate defaultInstance;
    public static Authenticate getDefaultInstance() {
      return defaultInstance;
    }
    
    public Authenticate getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tokbox.tumor.proto.OtspService.internal_static_otsp_Authenticate_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tokbox.tumor.proto.OtspService.internal_static_otsp_Authenticate_fieldAccessorTable;
    }
    
    public enum OpCode
        implements com.google.protobuf.ProtocolMessageEnum {
      CHALLENGE(0, 1),
      RESPONSE(1, 2),
      SUCCESS(2, 3),
      FAILURE(3, 4),
      ;
      
      public static final int CHALLENGE_VALUE = 1;
      public static final int RESPONSE_VALUE = 2;
      public static final int SUCCESS_VALUE = 3;
      public static final int FAILURE_VALUE = 4;
      
      
      public final int getNumber() { return value; }
      
      public static OpCode valueOf(int value) {
        switch (value) {
          case 1: return CHALLENGE;
          case 2: return RESPONSE;
          case 3: return SUCCESS;
          case 4: return FAILURE;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<OpCode>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<OpCode>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<OpCode>() {
              public OpCode findValueByNumber(int number) {
                return OpCode.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.tokbox.tumor.proto.OtspService.Authenticate.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final OpCode[] VALUES = {
        CHALLENGE, RESPONSE, SUCCESS, FAILURE, 
      };
      
      public static OpCode valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private OpCode(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:otsp.Authenticate.OpCode)
    }
    
    private int bitField0_;
    // optional .otsp.Authenticate.OpCode opcode = 1;
    public static final int OPCODE_FIELD_NUMBER = 1;
    private com.tokbox.tumor.proto.OtspService.Authenticate.OpCode opcode_;
    public boolean hasOpcode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.tokbox.tumor.proto.OtspService.Authenticate.OpCode getOpcode() {
      return opcode_;
    }
    
    // optional string content = 2;
    public static final int CONTENT_FIELD_NUMBER = 2;
    private java.lang.Object content_;
    public boolean hasContent() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          content_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      opcode_ = com.tokbox.tumor.proto.OtspService.Authenticate.OpCode.CHALLENGE;
      content_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      com.google.protobuf.GeneratedMessage
        .ExtendableMessage<com.tokbox.tumor.proto.OtspService.Authenticate>.ExtensionWriter extensionWriter =
          newExtensionWriter();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, opcode_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getContentBytes());
      }
      extensionWriter.writeUntil(536870912, output);
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, opcode_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getContentBytes());
      }
      size += extensionsSerializedSize();
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.tokbox.tumor.proto.OtspService.Authenticate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspService.Authenticate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspService.Authenticate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspService.Authenticate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspService.Authenticate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspService.Authenticate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspService.Authenticate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.tokbox.tumor.proto.OtspService.Authenticate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.tokbox.tumor.proto.OtspService.Authenticate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.tokbox.tumor.proto.OtspService.Authenticate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.tokbox.tumor.proto.OtspService.Authenticate prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.ExtendableBuilder<
          com.tokbox.tumor.proto.OtspService.Authenticate, Builder> implements com.tokbox.tumor.proto.OtspService.AuthenticateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tokbox.tumor.proto.OtspService.internal_static_otsp_Authenticate_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tokbox.tumor.proto.OtspService.internal_static_otsp_Authenticate_fieldAccessorTable;
      }
      
      // Construct using com.tokbox.tumor.proto.OtspService.Authenticate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        opcode_ = com.tokbox.tumor.proto.OtspService.Authenticate.OpCode.CHALLENGE;
        bitField0_ = (bitField0_ & ~0x00000001);
        content_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tokbox.tumor.proto.OtspService.Authenticate.getDescriptor();
      }
      
      public com.tokbox.tumor.proto.OtspService.Authenticate getDefaultInstanceForType() {
        return com.tokbox.tumor.proto.OtspService.Authenticate.getDefaultInstance();
      }
      
      public com.tokbox.tumor.proto.OtspService.Authenticate build() {
        com.tokbox.tumor.proto.OtspService.Authenticate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.tokbox.tumor.proto.OtspService.Authenticate buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.tokbox.tumor.proto.OtspService.Authenticate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.tokbox.tumor.proto.OtspService.Authenticate buildPartial() {
        com.tokbox.tumor.proto.OtspService.Authenticate result = new com.tokbox.tumor.proto.OtspService.Authenticate(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.opcode_ = opcode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.content_ = content_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tokbox.tumor.proto.OtspService.Authenticate) {
          return mergeFrom((com.tokbox.tumor.proto.OtspService.Authenticate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.tokbox.tumor.proto.OtspService.Authenticate other) {
        if (other == com.tokbox.tumor.proto.OtspService.Authenticate.getDefaultInstance()) return this;
        if (other.hasOpcode()) {
          setOpcode(other.getOpcode());
        }
        if (other.hasContent()) {
          setContent(other.getContent());
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!extensionsAreInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.tokbox.tumor.proto.OtspService.Authenticate.OpCode value = com.tokbox.tumor.proto.OtspService.Authenticate.OpCode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                opcode_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              content_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional .otsp.Authenticate.OpCode opcode = 1;
      private com.tokbox.tumor.proto.OtspService.Authenticate.OpCode opcode_ = com.tokbox.tumor.proto.OtspService.Authenticate.OpCode.CHALLENGE;
      public boolean hasOpcode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.tokbox.tumor.proto.OtspService.Authenticate.OpCode getOpcode() {
        return opcode_;
      }
      public Builder setOpcode(com.tokbox.tumor.proto.OtspService.Authenticate.OpCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        opcode_ = value;
        onChanged();
        return this;
      }
      public Builder clearOpcode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        opcode_ = com.tokbox.tumor.proto.OtspService.Authenticate.OpCode.CHALLENGE;
        onChanged();
        return this;
      }
      
      // optional string content = 2;
      private java.lang.Object content_ = "";
      public boolean hasContent() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setContent(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        content_ = value;
        onChanged();
        return this;
      }
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000002);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      void setContent(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        content_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:otsp.Authenticate)
    }
    
    static {
      defaultInstance = new Authenticate(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:otsp.Authenticate)
  }
  
  public static final int PUSH_FIELD_NUMBER = 100;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.tokbox.tumor.proto.OtspCore.OtspMessage,
      com.tokbox.tumor.proto.OtspService.Push> push = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.tokbox.tumor.proto.OtspService.Push.class,
        com.tokbox.tumor.proto.OtspService.Push.getDefaultInstance());
  public static final int PRESENCE_FIELD_NUMBER = 101;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.tokbox.tumor.proto.OtspCore.OtspMessage,
      com.tokbox.tumor.proto.OtspService.Presence> presence = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.tokbox.tumor.proto.OtspService.Presence.class,
        com.tokbox.tumor.proto.OtspService.Presence.getDefaultInstance());
  public static final int IQ_FIELD_NUMBER = 102;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.tokbox.tumor.proto.OtspCore.OtspMessage,
      com.tokbox.tumor.proto.OtspService.IQ> iq = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.tokbox.tumor.proto.OtspService.IQ.class,
        com.tokbox.tumor.proto.OtspService.IQ.getDefaultInstance());
  public static final int AUTHENTICATE_FIELD_NUMBER = 103;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.tokbox.tumor.proto.OtspCore.OtspMessage,
      com.tokbox.tumor.proto.OtspService.Authenticate> authenticate = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.tokbox.tumor.proto.OtspService.Authenticate.class,
        com.tokbox.tumor.proto.OtspService.Authenticate.getDefaultInstance());
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_otsp_Push_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_otsp_Push_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_otsp_Presence_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_otsp_Presence_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_otsp_IQ_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_otsp_IQ_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_otsp_Authenticate_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_otsp_Authenticate_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\0233otsp_service.proto\022\004otsp\032\0201otsp_root." +
      "proto\"\020\n\004Push*\010\010d\020\200\200\200\200\002\"\032\n\010Presence*\004\010\n\020" +
      "d*\010\010d\020\200\200\200\200\002\"\\\n\002IQ\022\033\n\004type\030\001 \001(\0162\r.otsp.I" +
      "Q.Type\"/\n\004Type\022\007\n\003SET\020\001\022\007\n\003GET\020\002\022\n\n\006RESU" +
      "LT\020\003\022\t\n\005ERROR\020\004*\010\010d\020\200\200\200\200\002\"\225\001\n\014Authentica" +
      "te\022)\n\006opcode\030\001 \001(\0162\031.otsp.Authenticate.O" +
      "pCode\022\017\n\007content\030\002 \001(\t\"?\n\006OpCode\022\r\n\tCHAL" +
      "LENGE\020\001\022\014\n\010RESPONSE\020\002\022\013\n\007SUCCESS\020\003\022\013\n\007FA" +
      "ILURE\020\004*\010\010d\020\200\200\200\200\002:+\n\004push\022\021.otsp.OtspMes" +
      "sage\030d \001(\0132\n.otsp.Push:3\n\010presence\022\021.ots",
      "p.OtspMessage\030e \001(\0132\016.otsp.Presence:\'\n\002i" +
      "q\022\021.otsp.OtspMessage\030f \001(\0132\010.otsp.IQ:;\n\014" +
      "authenticate\022\021.otsp.OtspMessage\030g \001(\0132\022." +
      "otsp.AuthenticateB%\n\026com.tokbox.tumor.pr" +
      "otoB\013OtspService"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_otsp_Push_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_otsp_Push_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_otsp_Push_descriptor,
              new java.lang.String[] { },
              com.tokbox.tumor.proto.OtspService.Push.class,
              com.tokbox.tumor.proto.OtspService.Push.Builder.class);
          internal_static_otsp_Presence_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_otsp_Presence_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_otsp_Presence_descriptor,
              new java.lang.String[] { },
              com.tokbox.tumor.proto.OtspService.Presence.class,
              com.tokbox.tumor.proto.OtspService.Presence.Builder.class);
          internal_static_otsp_IQ_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_otsp_IQ_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_otsp_IQ_descriptor,
              new java.lang.String[] { "Type", },
              com.tokbox.tumor.proto.OtspService.IQ.class,
              com.tokbox.tumor.proto.OtspService.IQ.Builder.class);
          internal_static_otsp_Authenticate_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_otsp_Authenticate_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_otsp_Authenticate_descriptor,
              new java.lang.String[] { "Opcode", "Content", },
              com.tokbox.tumor.proto.OtspService.Authenticate.class,
              com.tokbox.tumor.proto.OtspService.Authenticate.Builder.class);
          push.internalInit(descriptor.getExtensions().get(0));
          presence.internalInit(descriptor.getExtensions().get(1));
          iq.internalInit(descriptor.getExtensions().get(2));
          authenticate.internalInit(descriptor.getExtensions().get(3));
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.tokbox.tumor.proto.OtspCore.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
